export const posts = [
  {
    id: 1,
    title: "Why Learning to Code is Essential in 2024",
    content: "Coding has become an essential skill in the modern world. Whether you're a student, entrepreneur, or in any profession, learning to code can open up numerous opportunities...",
    author: "Nifad Uzzaman",
    userName: "nifad_uzzaman",
    date: "2024-09-20",
    views: 0,
  },
  {
    id: 2,
    title: "Top 10 JavaScript Libraries for Frontend Development",
    content: "JavaScript libraries make frontend development easier and faster. In this blog, we explore the top 10 libraries that every frontend developer should know in 2024...",
    author: "Sara Ahmed",
    userName: "sara_ahmed",
    date: "2024-09-21",
    views: 0,
  },
  {
    id: 3,
    title: "How to Get Started with React Native",
    content: "React Native is a powerful framework for building cross-platform mobile apps. Here's a beginner's guide to getting started with React Native and understanding its core concepts...",
    author: "David Johnson",
    userName: "david_johnson",
    date: "2024-09-22",
    views: 0,
  },
  {
    id: 4,
    title: "Understanding Tailwind CSS: A Complete Guide",
    content: "Tailwind CSS is a utility-first CSS framework that has taken the frontend world by storm. In this blog, we break down how it works, why it's popular, and how you can use it in your next project...",
    author: "Emma Brown",
    userName: "emma_brown",
    date: "2024-09-23",
    views: 0,
  },
  {
    id: 5,
    title: "5 Tips for Better Time Management as a Developer",
    content: "Time management is crucial for developers, especially with multiple deadlines and projects. Here are five effective tips to boost your productivity and manage your time better...",
    author: "Nifad Uzzaman",
    userName: "nifad_uzzaman",
    date: "2024-09-24",
    views: 0,
  },
  {
    id: 6,
    title: "Building a Simple To-Do App with Next.js",
    content: "Next.js is a powerful React framework that makes building applications fast and efficient. In this tutorial, we will build a simple to-do app using Next.js and TypeScript...",
    author: "Emily Clark",
    userName: "emily_clark",
    date: "2024-09-25",
    views: 0,
  },
  {
    id: 7,
    title: "The Importance of Mental Health for Developers",
    content: "Developers often face burnout and stress due to long hours and tight deadlines. In this blog, we discuss the importance of mental health and ways to maintain balance while coding...",
    author: "Mohammed Ali",
    userName: "mohammed_ali",
    date: "2024-09-26",
    views: 0,
  },
  {
    id: 8,
    title: "What’s New in JavaScript ES2024?",
    content: "JavaScript evolves every year with new features and updates. ES2024 brings exciting changes to the language, from new syntax to improved performance. Let's dive into what's new...",
    author: "John Doe",
    userName: "john_doe",
    date: "2024-09-27",
    views: 0,
  },
  {
    id: 9,
    title: "How to Improve Your Problem-Solving Skills in Programming",
    content: "Programming is as much about problem-solving as it is about writing code. Here are some tips and strategies to help you improve your problem-solving skills in coding...",
    author: "Sara Ahmed",
    userName: "sara_ahmed",
    date: "2024-09-28",
    views: 0,
  },
  {
    id: 10,
    title: "Exploring the World of Machine Learning in 2024",
    content: "Machine learning continues to grow in popularity, and it's changing industries across the globe. This blog explores the basics of machine learning and how you can get started in 2024...",
    author: "Emily Clark",
    userName: "emily_clark",
    date: "2024-09-29",
    views: 0,
  },
  {
    id: 11,
    title: "How to Build a Blog App with Next.js and Tailwind CSS",
    content: "In this blog, we walk through the process of building a simple blog application using Next.js and Tailwind CSS. You’ll learn how to structure your project, add routing, and more...",
    author: "David Johnson",
    userName: "david_johnson",
    date: "2024-09-30",
    views: 0,
  },
  {
    id: 12,
    title: "The Benefits of Pair Programming",
    content: "Pair programming is a technique where two developers work together on the same task. In this blog, we discuss the benefits of pair programming and how it can enhance your skills...",
    author: "Emma Brown",
    userName: "emma_brown",
    date: "2024-10-01",
    views: 0,
  },
  {
    id: 13,
    title: "5 Common Mistakes to Avoid as a Beginner Programmer",
    content: "Starting as a programmer can be overwhelming, and mistakes are part of the process. Here are five common mistakes beginner programmers make and how to avoid them...",
    author: "Mohammed Ali",
    userName: "mohammed_ali",
    date: "2024-10-02",
    views: 0,
  },
  {
    id: 14,
    title: "Introduction to Git and GitHub for Version Control",
    content: "Git and GitHub are essential tools for developers. In this blog, we cover the basics of version control, how to use Git, and how to collaborate with others on GitHub...",
    author: "John Doe",
    userName: "john_doe",
    date: "2024-10-03",
    views: 0,
  },
  {
    id: 15,
    title: "10 Tips for Writing Clean Code",
    content: "Clean code is readable, maintainable, and easier to work with. Here are 10 tips to help you write cleaner code that both you and other developers will appreciate...",
    author: "Nifad Uzzaman",
    userName: "nifad_uzzaman",
    date: "2024-10-04",
    views: 0,
  },
  {
    id: 16,
    title: "How to Optimize Web Performance in 2024",
    content: "In 2024, web performance remains a critical factor in user experience. Learn about the latest techniques to optimize web performance and improve load times...",
    author: "David Johnson",
    userName: "david_johnson",
    date: "2024-10-05",
    views: 0,
  },
  {
    id: 17,
    title: "Understanding TypeScript Generics",
    content: "Generics in TypeScript provide a way to create reusable code that works with any type. This blog breaks down how to use generics and their benefits in TypeScript...",
    author: "Sara Ahmed",
    userName: "sara_ahmed",
    date: "2024-10-06",
    views: 0,
  },
  {
    id: 18,
    title: "The Future of Frontend Development in 2024",
    content: "Frontend development continues to evolve with new technologies and practices. Here's a look at what we can expect from the world of frontend development in 2024...",
    author: "Emily Clark",
    userName: "emily_clark",
    date: "2024-10-07",
    views: 0,
  },
  {
    id: 19,
    title: "Building a Portfolio Website Using Next.js",
    content: "A portfolio website is essential for developers to showcase their work. In this blog, we explore how to build a stunning portfolio site using Next.js and Tailwind CSS...",
    author: "Mohammed Ali",
    userName: "mohammed_ali",
    date: "2024-10-08",
    views: 0,
  },
  {
    id: 20,
    title: "How to Contribute to Open Source Projects",
    content: "Contributing to open source projects is a great way to improve your skills and give back to the community. Learn how to find projects and start contributing today...",
    author: "John Doe",
    userName: "john_doe",
    date: "2024-10-09",
    views: 0,
  }
];
